### ISSUE TITLE
Integration stopped working in Home Assistant 2024.5.3

### ISSUE THREAD

**Issue by eyalpost** [hllhll/HomeAssistant-ekon-local#30]
Getting the following error in the log:

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:580
integration: Climate (documentation, issues)
First occurred: 09:40:37 (1 occurrences)
Last logged: 09:40:37

Error adding entity climate.kitchenac for domain climate with platform ekon-local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1359, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'ekon-local' calls async_write_ha_state from a thread at custom_components/ekon-local/climate.py, line 187: self._async_add_devices([newdev]). Please report it to the author of the 'ekon-local' custom integration.
```

**Comment by eyalpost** [comment]
Looks like a PR is already pending: https://github.com/hllhll/HomeAssistant-ekon-local/pull/29
