### ISSUE TITLE
HA Freeze after couple of hour

### ISSUE THREAD

**Issue by leranp** [hllhll/HomeAssistant-ekon-local#8]
HA Freeze after couple of hour with the new version this component , tried 3 time and same result .

```
2020-11-27 00:54:44 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - Scheduling update
2020-11-27 00:54:44 DEBUG (MainThread) [custom_components.ekon-local.climate] EkonLocalClimate.update_state
2020-11-27 00:54:44 INFO (MainThread) [custom_components.ekon-local.climate] hvac_mode(): off
2020-11-27 00:54:44 INFO (MainThread) [custom_components.ekon-local.climate] current_temperature(): 24.0
2020-11-27 00:54:44 INFO (MainThread) [custom_components.ekon-local.climate] target_temperature(): 25.0
2020-11-27 00:54:44 INFO (MainThread) [custom_components.ekon-local.climate] fan_mode(): 1
2020-11-27 00:54:44 INFO (MainThread) [custom_components.ekon-local.climate] name(): ekon3365
2020-11-27 00:54:44 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - update scheduled
2020-11-27 00:54:48 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - Scheduling update
2020-11-27 00:54:48 DEBUG (MainThread) [custom_components.ekon-local.climate] EkonLocalClimate.update_state
2020-11-27 00:54:48 INFO (MainThread) [custom_components.ekon-local.climate] hvac_mode(): off
2020-11-27 00:54:48 INFO (MainThread) [custom_components.ekon-local.climate] current_temperature(): 24.0
2020-11-27 00:54:48 INFO (MainThread) [custom_components.ekon-local.climate] target_temperature(): 25.0
2020-11-27 00:54:48 INFO (MainThread) [custom_components.ekon-local.climate] fan_mode(): 1
2020-11-27 00:54:48 INFO (MainThread) [custom_components.ekon-local.climate] name(): ekon3365
2020-11-27 00:54:48 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - update scheduled
2020-11-27 00:55:00 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 320, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 312, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 133, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1812, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration
2020-11-27 00:55:00 ERROR (SyncWorker_7) [concurrent.futures] exception calling callback for <Future at 0x66701c70 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.8/asyncio/futures.py", line 374, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 764, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by hllhll** [comment]
Finally saw this myself, might be misuse/mixup of threads & Async... hope to check this soon

**Comment by hllhll** [comment]
This _might_ be the issue... 
https://github.com/hllhll/pyekonlib/blob/eb1424a0c9242be02f5bc16399f210f8b722f510/pyekonlib/Server.py#L84
Calls `self._createAsyncTaskFn` which maps to `hass.async_create_task` in https://github.com/hllhll/HomeAssistant-ekon-local/blob/master/custom_components/ekon-local/climate.py#L161 which [should be used to create async task from async](https://developers.home-assistant.io/docs/asyncio_working_with_async/#starting-independent-task-from-async). for thread we should use [this(?)](https://developers.home-assistant.io/docs/asyncio_working_with_async/#calling-async-functions-from-threads)

**Comment by hllhll** [comment]
Please try with this fix and report back if you can...

**Comment by leranp** [comment]
> Please try with this fix and report back if you can...

no problem , I will update you soon

**Comment by hllhll** [comment]
Got a report from one user that so far, problem doesn't persist after the fix :)

**Comment by leranp** [comment]
> Got a report from one user that so far, problem doesn't persist after the fix :)

it took time, but unfortunately the problem appear after 18 hour :-(

```2020-12-13 18:34:19 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - Scheduling update
2020-12-13 18:34:19 DEBUG (MainThread) [custom_components.ekon-local.climate] EkonLocalClimate.update_state
2020-12-13 18:34:19 INFO (MainThread) [custom_components.ekon-local.climate] hvac_mode(): off
2020-12-13 18:34:19 INFO (MainThread) [custom_components.ekon-local.climate] current_temperature(): 24.0
2020-12-13 18:34:19 INFO (MainThread) [custom_components.ekon-local.climate] target_temperature(): 25.0
2020-12-13 18:34:19 INFO (MainThread) [custom_components.ekon-local.climate] fan_mode(): 1
2020-12-13 18:34:19 INFO (MainThread) [custom_components.ekon-local.climate] name(): ekon3365
2020-12-13 18:34:19 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - update scheduled
2020-12-13 18:34:24 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - Scheduling update
2020-12-13 18:34:24 DEBUG (MainThread) [custom_components.ekon-local.climate] EkonLocalClimate.update_state
2020-12-13 18:34:24 INFO (MainThread) [custom_components.ekon-local.climate] hvac_mode(): off
2020-12-13 18:34:24 INFO (MainThread) [custom_components.ekon-local.climate] current_temperature(): 24.0
2020-12-13 18:34:24 INFO (MainThread) [custom_components.ekon-local.climate] target_temperature(): 25.0
2020-12-13 18:34:24 INFO (MainThread) [custom_components.ekon-local.climate] fan_mode(): 1
2020-12-13 18:34:24 INFO (MainThread) [custom_components.ekon-local.climate] name(): ekon3365
2020-12-13 18:34:24 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - update scheduled
2020-12-13 18:34:35 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - Scheduling update
2020-12-13 18:34:35 DEBUG (MainThread) [custom_components.ekon-local.climate] EkonLocalClimate.update_state
2020-12-13 18:34:35 INFO (MainThread) [custom_components.ekon-local.climate] hvac_mode(): off
2020-12-13 18:34:35 INFO (MainThread) [custom_components.ekon-local.climate] current_temperature(): 24.0
2020-12-13 18:34:35 INFO (MainThread) [custom_components.ekon-local.climate] target_temperature(): 25.0
2020-12-13 18:34:35 INFO (MainThread) [custom_components.ekon-local.climate] fan_mode(): 1
2020-12-13 18:34:35 INFO (MainThread) [custom_components.ekon-local.climate] name(): ekon3365
2020-12-13 18:34:35 DEBUG (MainThread) [custom_components.ekon-local.climate] Ekon HVAC data recived - update scheduled
2020-12-13 18:34:43 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 320, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 312, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 133, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1812, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration```

**Comment by leranp** [comment]
https://github.com/python/asyncio/issues/258

Look like the same problem here

**Comment by hllhll** [comment]
Why di you think it's necessarily this?
I guess this situatuon might arise from multiple different issue origins. 

BTW Do u might have other integration that is async based+threads? That might be due to a conflict originated from a different integration...

**Comment by hllhll** [comment]
I have installed another integration for my ha
It seem to happen more often. 
I assume that having more integrations gives the random-by-nature race condition more chances to occur...

**Comment by hllhll** [comment]
With the help of a friend, We might have found the issue and fixed it in https://github.com/hllhll/pyekonlib/commit/96d923a6263029b79a4c65a0cd7bb24a916da351 and corresponding fix in https://github.com/hllhll/HomeAssistant-ekon-local/commit/0c0b2a9f53841b6114ae554d67c286e32d40b073

**Comment by hllhll** [comment]
I Had this issue again, not sure if it's related to my integration, so I'm re-opening it for the meantime
I plan to implement verbose logging in pyekonlib ...

**Comment by hllhll** [comment]
Let's see if this helps ...
https://github.com/hllhll/HomeAssistant-ekon-local/commit/429cc3abece9131a8ec2123d8446e718a41d7bc6
This is not ideal, because it actually creates another-mostly idle OS thread, but that's my temporary way to circumvent this issue

**Comment by hllhll** [comment]
The way of implementation for a fix for this in pyekonlib, is not the best.
If someone could go over the code and find the actual issue, I'd like that :)
But when using commit https://github.com/hllhll/HomeAssistant-ekon-local/commit/429cc3abece9131a8ec2123d8446e718a41d7bc6 This does not happen again.
